import { useState } from "react";
import { Box, Stack, Typography, Alert, CircularProgress } from "@mui/material";
import { analyzeFile, type FileItem, type AnalyzeResult, type ApiError } from "../../api/api";
import { fileKind } from "../../utils/util";
import { useAuth } from "../auth/useAuth";
import { useAiPrefs } from "../../hooks/useAiPrefs";
import { Icon, Icons } from "../../components/icons";
import { MONO_FONT } from "../../theme";

interface Props {
  file: FileItem;
}

function describeError(status: number | undefined, message?: string): { severity: "info" | "warning" | "error"; text: string } {
  switch (status) {
    case 403:
      return { severity: "warning", text: message || "You can't analyze this file." };
    case 503:
      return { severity: "info", text: "AI analysis isn't available right now." };
    case 422:
      return { severity: "warning", text: "The model couldn't describe this file." };
    case 415:
      return { severity: "warning", text: "This file type can't be analyzed." };
    case 413:
      return { severity: "warning", text: "Image too large to analyze." };
    case 429:
      return { severity: "warning", text: "Too many analyses in progress - try again in a moment." };
    default:
      return { severity: "error", text: "Couldn't analyze this file. Please try again." };
  }
}

export default function AiAnalysisCard({ file }: Props) {
  const token = useAuth((s) => s.token)!;
  const analysisOn = useAiPrefs((s) => s.analysis);
  const aiAvailable = useAiPrefs((s) => s.aiStatus.ai);
  const [result, setResult] = useState<AnalyzeResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<{ severity: "info" | "warning" | "error"; text: string } | null>(null);

  const kind = fileKind(file.mime_type, file.original_name);
  const supported = kind === "image" || kind === "text" || kind === "code";

  if (!supported || !analysisOn || !aiAvailable) return null;

  async function run(refresh: boolean) {
    setLoading(true);
    setErr(null);
    try {
      const res = await analyzeFile(token, file.id, refresh);
      setResult(res);
    } catch (e) {
      setErr(describeError((e as ApiError).status, (e as ApiError).message));
    } finally {
      setLoading(false);
    }
  }

  return (
    <Box
      sx={(t) => ({
        borderRadius: "9px",
        p: 2.25,
        border: "1px solid",
        borderColor: t.colors.aiBorder,
        background: t.colors.surface,
      })}
    >

      <Stack direction="row" alignItems="center" spacing={1.125}>
        <Icon
          name={Icons.autoAwesome}
          size={20}
          fill
          sx={(t) => ({ color: t.colors.aiIcon })}
        />
        <Typography
          sx={(t) => ({
            fontFamily: '"Space Grotesk", sans-serif',
            fontWeight: 700,
            fontSize: 14,
            letterSpacing: "-0.01em",
            color: t.palette.mode === "light" ? t.palette.primary.main : t.colors.aiHeading,
            flexGrow: 1,
          })}
        >
          AI analysis
        </Typography>
      </Stack>

      {!result && !err && (
        <Box
          component="button"
          onClick={() => run(false)}
          disabled={loading}
          sx={(t) => ({
            mt: 1.5, width: "100%", minHeight: 44, cursor: loading ? "default" : "pointer",
            display: "flex", alignItems: "center", justifyContent: "center", gap: 1,
            borderRadius: "7px", border: "none",
            bgcolor: t.colors.primaryTint,
            color: t.palette.primary.main,
            fontFamily: '"Hanken Grotesk", sans-serif', fontWeight: 600, fontSize: 13.5,
            "&:hover": { filter: "brightness(0.97)" },
          })}
        >
          {loading && <CircularProgress size={16} sx={{ color: "primary.main" }} />}
          {loading ? "Analyzing…" : "Analyze with AI"}
        </Box>
      )}

      {err && <Alert severity={err.severity} sx={{ mt: 1.5 }}>{err.text}</Alert>}

      {result && (
        <>
          <Typography
            sx={(t) => ({
              fontFamily: '"Hanken Grotesk", sans-serif',
              fontSize: 13,
              lineHeight: 1.55,
              color: t.colors.body,
              mt: 1.5,
              whiteSpace: "pre-wrap",
            })}
          >
            {result.summary}
          </Typography>

          <Stack direction="row" alignItems="center" sx={{ mt: 1.75 }}>
            <Box sx={{ fontFamily: MONO_FONT, fontWeight: 500, fontSize: 10.5, color: "text.disabled", flexGrow: 1 }}>
              {result.cached ? "Saved result" : `Generated by ${result.model}`}
            </Box>
            <Box
              component="button"
              onClick={() => run(true)}
              disabled={loading}
              sx={{
                display: "inline-flex", alignItems: "center", gap: 0.625, cursor: loading ? "default" : "pointer",
                border: "none", background: "transparent", p: 0,
                fontFamily: '"Hanken Grotesk", sans-serif', fontWeight: 600, fontSize: 12, color: "primary.main",
              }}
            >
              {loading ? (
                <CircularProgress size={13} sx={{ color: "primary.main" }} />
              ) : (
                <Icon name={Icons.refresh} size={15} />
              )}
              Regenerate
            </Box>
          </Stack>
        </>
      )}
    </Box>
  );
}
