// AUTO-GENERATED by shared/generate.mjs from shared/contract.json - DO NOT EDIT.
// Run `node shared/generate.mjs` (or `npm run tokens`) to regenerate.

export const SHAREPERMISSION = ["view", "save"] as const;
export type SharePermission = (typeof SHAREPERMISSION)[number];
