import * as cc from "./sodiumcrypto";
import * as uk from "./userkeys";
import * as fc from "./filecrypto";
import { writeFileSync } from "fs";
import { join } from "path";

async function main() {
  await cc.ready();
  let pass = 0, fail = 0;
  const check = (n: string, c: boolean) => { c ? pass++ : fail++; console.log(`  ${c ? "PASS" : "FAIL"} ${n}`); };
  const eq = (a: Buffer, b: Buffer) => Buffer.compare(a, b) === 0;

  const salt = Buffer.alloc(16, 0x11), seed = Buffer.alloc(32, 0x22);
  const vaultKey = cc.deriveVaultKey("example-vector-password", salt);
  check("argon2id vector stable", vaultKey.toString("hex") === "86d411ac021f9bfe41d9f0d19951deb759ba8fca806fa3576f48df339d670d20");
  const kp = cc.keypairFromSeed(seed);
  check("seed keypair vector stable", kp.publicKey.toString("hex") === "9d8d78b9c9e6661e552f2f1af02095ee2f8743fa2e6183f41bb7077ef51b5379");

  const u = uk.createUserKeys("s3cret-pass");
  const skFromPw = uk.privateKeyFromPassword("s3cret-pass", u.salt, u.encryptedPrivateKey);
  const skFromRec = uk.privateKeyFromRecovery(u.recoveryCode, u.recoveryEncryptedPrivateKey);
  check("password unlock == recovery unlock", eq(skFromPw, skFromRec));
  let wrongRejected = false; try { uk.privateKeyFromPassword("nope", u.salt, u.encryptedPrivateKey); } catch { wrongRejected = true; }
  check("wrong password rejected", wrongRejected);

  const newVault = uk.rewrapForNewPassword(skFromPw, "brand-new-pass", u.salt);
  check("change-password re-wrap opens under new password", eq(uk.privateKeyFromPassword("brand-new-pass", u.salt, newVault), skFromPw));

  const dek = cc.generateDek();
  check("owner unwraps own sealed DEK", eq(uk.unwrapDek(uk.wrapDekFor(dek, u.publicKey), u.publicKey, skFromPw), dek));
  const recip = uk.createUserKeys("recip-pass");
  const recipSk = uk.privateKeyFromPassword("recip-pass", recip.salt, recip.encryptedPrivateKey);
  const wrappedForRecip = uk.wrapDekFor(dek, recip.publicKey);
  check("recipient unwraps shared DEK", eq(uk.unwrapDek(wrappedForRecip, recip.publicKey, recipSk), dek));
  let strangerDenied = false; try { uk.unwrapDek(wrappedForRecip, u.publicKey, skFromPw); } catch { strangerDenied = true; }
  check("stranger cannot unwrap", strangerDenied);

  const vDek = Buffer.alloc(32, 0x55);
  const vPrefix = Buffer.alloc(7, 0x66);
  const vPlain = Buffer.from("CloudCast CCE3 interop vector - chunked AES-256-GCM.", "utf8");
  const vChunk = 20;
  const cce3 = fc.encryptFileWithPrefix(vPlain, vDek, vPrefix, vChunk);
  check("cce3 roundtrip", eq(fc.decryptFile(cce3, vDek), vPlain));
  check("cce3 multi-chunk vector", cce3.length === 23 + vPlain.length + 3 * 16);
  check("cce3 range read", eq(fc.decryptRange(cce3, vDek, 10, 29), vPlain.subarray(10, 30)));
  let cce3Tamper = false;
  try { const t = Buffer.from(cce3); t[30] ^= 1; fc.decryptFile(t, vDek); } catch { cce3Tamper = true; }
  check("cce3 rejects tampering", cce3Tamper);

  const vectors = {
    note: "Interop gate for web (libsodium WASM) + Android (lazysodium). Fixed inputs -> expected hex. Regenerated by cryptocore.test.ts.",
    params: { argon2id: cc.ARGON2ID, sealedBoxBytes: 80, secretboxNonceBytes: 24 },
    inputs: {
      password: "example-vector-password",
      salt_hex: "11".repeat(16), keypair_seed_hex: "22".repeat(32),
      recovery_key_hex: "33".repeat(32), secretbox_nonce_hex: "44".repeat(24), dek_hex: "55".repeat(32),
      cce3_nonce_prefix_hex: "66".repeat(7),
      cce3_chunk_size: vChunk,
      cce3_plaintext_utf8: vPlain.toString("utf8"),
    },
    expected: {
      argon2id_vaultKey: vaultKey.toString("hex"),
      userPK: kp.publicKey.toString("hex"),
      userSK: kp.privateKey.toString("hex"),
      recoveryKdfKey: cc.recoveryVaultKey(Buffer.alloc(32, 0x33)).toString("hex"),
      secretbox_ct: cc.secretboxSealWithNonce(kp.privateKey, vaultKey, Buffer.alloc(24, 0x44)).toString("hex"),
      cce3_ciphertext: cce3.toString("hex"),
    },
  };
  writeFileSync(join(__dirname, "test-vectors.json"), JSON.stringify(vectors, null, 2));

  console.log(`\nRESULT: ${pass} passed, ${fail} failed`);
  process.exit(fail ? 1 : 0);
}
main();
