// AUTO-GENERATED by shared/generate.mjs from shared/contract.json - DO NOT EDIT.
// Run `node shared/generate.mjs` (also runs as a Gradle preBuild task) to regenerate.

package com.cloudcast.app.core

enum class SharePermission(val wire: String) {
    View("view"),
    Save("save"),
    ;
    override fun toString() = wire
    companion object {
        fun from(wire: String): SharePermission? = entries.firstOrNull { it.wire == wire }
    }
}
