// AUTO-GENERATED by shared/generate.mjs from shared/formats.json - DO NOT EDIT.
// Run `node shared/generate.mjs` (also runs as a Gradle preBuild task) to regenerate.

package com.cloudcast.app.core

/** Extension -> file kind. Shared so both clients classify a file identically. */
object Formats {
    val IMAGE_EXTS: Set<String> = setOf("avif", "bmp", "gif", "heic", "heif", "ico", "jpeg", "jpg", "png", "svg", "tif", "tiff", "webp")
    val VIDEO_EXTS: Set<String> = setOf("3gp", "avi", "flv", "m4v", "mkv", "mov", "mp4", "mpeg", "mpg", "webm", "wmv")
    val AUDIO_EXTS: Set<String> = setOf("aac", "flac", "m4a", "mp3", "ogg", "opus", "wav", "wma")
    val ARCHIVE_EXTS: Set<String> = setOf("7z", "bz2", "gz", "rar", "tar", "tgz", "xz", "zip")
    val DOC_EXTS: Set<String> = setOf("accdb", "accde", "doc", "docm", "docx", "dot", "dotm", "dotx", "gdoc", "gsheet", "gslides", "hwp", "key", "mdb", "numbers", "odf", "odg", "odp", "ods", "odt", "otp", "ots", "ott", "oxps", "pages", "pot", "potx", "pps", "ppsx", "ppt", "pptm", "pptx", "pub", "rtf", "wpd", "wps", "xls", "xlsb", "xlsm", "xlsx", "xlt", "xltm", "xltx", "xps")
    val CODE_EXTS: Set<String> = setOf("bash", "c", "cpp", "cs", "css", "go", "h", "hpp", "htm", "html", "java", "js", "json", "jsx", "kt", "kts", "php", "py", "rb", "rs", "scss", "sh", "sql", "swift", "toml", "ts", "tsx", "xml", "yaml", "yml")
    val TEXT_EXTS: Set<String> = setOf("cfg", "conf", "csv", "env", "ini", "log", "markdown", "md", "tsv", "txt")

    /** Keys inside the sealed {name, mime} envelope in files.meta_enc / meta_sealed. */
    const val META_NAME_KEY = "n"
    const val META_MIME_KEY = "m"
    const val DEFAULT_MIME = "application/octet-stream"

    /** Cross-device sign-in code. Crockford Base32 minus I/L/O/U; lookalikes are NOT substituted. */
    const val CODE_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
    const val CODE_LENGTH = 8
    const val CODE_GROUP = 4

    /** kind values for the sealed per-user blob store (user_blobs). */
    const val BLOB_KIND_FAVORITES = "favorites"

    /** Search query word -> file kinds it filters to. Shared so typing 'wallpaper' or 'notes' narrows the same way on both clients. */
    val SEARCH_WORDS: Map<String, Set<String>> = mapOf(
        "archive" to setOf("archive"),
        "archives" to setOf("archive"),
        "audio" to setOf("audio"),
        "backup" to setOf("archive"),
        "backups" to setOf("archive"),
        "clip" to setOf("video"),
        "clips" to setOf("video"),
        "code" to setOf("code"),
        "doc" to setOf("doc", "pdf", "text"),
        "docs" to setOf("doc", "pdf", "text"),
        "document" to setOf("doc", "pdf", "text"),
        "documents" to setOf("doc", "pdf", "text"),
        "film" to setOf("video"),
        "films" to setOf("video"),
        "footage" to setOf("video"),
        "icon" to setOf("image"),
        "image" to setOf("image"),
        "images" to setOf("image"),
        "movie" to setOf("video"),
        "movies" to setOf("video"),
        "music" to setOf("audio"),
        "note" to setOf("doc", "text"),
        "notes" to setOf("text"),
        "paper" to setOf("doc", "pdf", "text"),
        "papers" to setOf("doc", "pdf", "text"),
        "pdf" to setOf("pdf"),
        "pdfs" to setOf("pdf"),
        "photo" to setOf("image"),
        "photos" to setOf("image"),
        "pic" to setOf("image"),
        "pics" to setOf("image"),
        "picture" to setOf("image"),
        "pictures" to setOf("image"),
        "podcast" to setOf("audio"),
        "presentation" to setOf("doc"),
        "program" to setOf("code"),
        "recording" to setOf("audio", "video"),
        "recordings" to setOf("audio", "video"),
        "report" to setOf("doc", "pdf", "text"),
        "reports" to setOf("doc", "pdf", "text"),
        "screenshot" to setOf("image"),
        "screenshots" to setOf("image"),
        "script" to setOf("code"),
        "scripts" to setOf("code"),
        "sheet" to setOf("doc"),
        "slides" to setOf("doc"),
        "song" to setOf("audio"),
        "songs" to setOf("audio"),
        "sound" to setOf("audio"),
        "sounds" to setOf("audio"),
        "source" to setOf("code"),
        "spreadsheet" to setOf("doc"),
        "text" to setOf("text"),
        "track" to setOf("audio"),
        "tracks" to setOf("audio"),
        "video" to setOf("video"),
        "videos" to setOf("video"),
        "voice" to setOf("audio"),
        "wallpaper" to setOf("image"),
        "zip" to setOf("archive"),
        "zips" to setOf("archive"),
    )

    /** File kind -> auto-file folder name. Shared so the same upload lands in the same folder on both clients. A kind with no folder is not auto-filed. */
    val KIND_FOLDERS: Map<String, String> = mapOf(
        "image" to "Images",
        "video" to "Videos",
        "audio" to "Audio",
        "pdf" to "Documents",
        "doc" to "Documents",
        "text" to "Documents",
        "code" to "Code",
        "archive" to "Archives",
    )

    /** Folder-name synonym groups for smart auto-filing. Two names that share a group describe the same concept, so an AI suggestion of 'Screenshots' can match an existing 'Pictures' folder. Shared so both clients match the same way. */
    val FOLDER_CONCEPTS: List<Set<String>> = listOf(
        setOf("image", "picture", "photo", "pic", "snapshot", "wallpaper", "screenshot", "screengrab", "screencap"),
        setOf("screenshot", "screengrab", "screencap", "screencapture"),
        setOf("video", "movie", "film", "clip", "footage", "recording"),
        setOf("audio", "music", "song", "sound", "soundtrack", "track", "podcast", "voice"),
        setOf("document", "doc", "pdf", "paper", "letter", "report", "file"),
        setOf("receipt", "invoice", "bill"),
        setOf("code", "source", "script", "program", "snippet", "dev"),
        setOf("archive", "zip", "backup", "compressed"),
        setOf("note", "memo"),
        setOf("data", "dataset", "csv", "spreadsheet", "sheet"),
        setOf("diagram", "chart", "graph", "figure"),
    )
}
