// AUTO-GENERATED by shared/generate.mjs from shared/formats.json - DO NOT EDIT.
// Run `node shared/generate.mjs` (or `npm run tokens`) to regenerate.

/** Extension -> file kind. Shared so both clients classify a file identically. */
export const IMAGE_EXTS: readonly string[] = ["avif", "bmp", "gif", "heic", "heif", "ico", "jpeg", "jpg", "png", "svg", "tif", "tiff", "webp"];
export const VIDEO_EXTS: readonly string[] = ["3gp", "avi", "flv", "m4v", "mkv", "mov", "mp4", "mpeg", "mpg", "webm", "wmv"];
export const AUDIO_EXTS: readonly string[] = ["aac", "flac", "m4a", "mp3", "ogg", "opus", "wav", "wma"];
export const ARCHIVE_EXTS: readonly string[] = ["7z", "bz2", "gz", "rar", "tar", "tgz", "xz", "zip"];
export const DOC_EXTS: readonly string[] = ["accdb", "accde", "doc", "docm", "docx", "dot", "dotm", "dotx", "gdoc", "gsheet", "gslides", "hwp", "key", "mdb", "numbers", "odf", "odg", "odp", "ods", "odt", "otp", "ots", "ott", "oxps", "pages", "pot", "potx", "pps", "ppsx", "ppt", "pptm", "pptx", "pub", "rtf", "wpd", "wps", "xls", "xlsb", "xlsm", "xlsx", "xlt", "xltm", "xltx", "xps"];
export const CODE_EXTS: readonly string[] = ["bash", "c", "cpp", "cs", "css", "go", "h", "hpp", "htm", "html", "java", "js", "json", "jsx", "kt", "kts", "php", "py", "rb", "rs", "scss", "sh", "sql", "swift", "toml", "ts", "tsx", "xml", "yaml", "yml"];
export const TEXT_EXTS: readonly string[] = ["cfg", "conf", "csv", "env", "ini", "log", "markdown", "md", "tsv", "txt"];

/** Keys inside the sealed {name, mime} envelope in files.meta_enc / meta_sealed. */
export const META = { nameKey: "n", mimeKey: "m", defaultMime: "application/octet-stream" } as const;

/** Cross-device sign-in code. Crockford Base32 minus I/L/O/U; lookalikes are NOT substituted. */
export const SIGN_IN_CODE = { alphabet: "0123456789ABCDEFGHJKMNPQRSTVWXYZ", length: 8, group: 4 } as const;

/** kind values for the sealed per-user blob store (user_blobs). */
export const BLOB_KIND = { favorites: "favorites" } as const;

/** Search query word -> file kinds it filters to. Shared so typing 'wallpaper' or 'notes' narrows the same way on both clients. */
export const SEARCH_WORDS: Readonly<Record<string, readonly string[]>> = {
  archive: ["archive"],
  archives: ["archive"],
  audio: ["audio"],
  backup: ["archive"],
  backups: ["archive"],
  clip: ["video"],
  clips: ["video"],
  code: ["code"],
  doc: ["doc", "pdf", "text"],
  docs: ["doc", "pdf", "text"],
  document: ["doc", "pdf", "text"],
  documents: ["doc", "pdf", "text"],
  film: ["video"],
  films: ["video"],
  footage: ["video"],
  icon: ["image"],
  image: ["image"],
  images: ["image"],
  movie: ["video"],
  movies: ["video"],
  music: ["audio"],
  note: ["doc", "text"],
  notes: ["text"],
  paper: ["doc", "pdf", "text"],
  papers: ["doc", "pdf", "text"],
  pdf: ["pdf"],
  pdfs: ["pdf"],
  photo: ["image"],
  photos: ["image"],
  pic: ["image"],
  pics: ["image"],
  picture: ["image"],
  pictures: ["image"],
  podcast: ["audio"],
  presentation: ["doc"],
  program: ["code"],
  recording: ["audio", "video"],
  recordings: ["audio", "video"],
  report: ["doc", "pdf", "text"],
  reports: ["doc", "pdf", "text"],
  screenshot: ["image"],
  screenshots: ["image"],
  script: ["code"],
  scripts: ["code"],
  sheet: ["doc"],
  slides: ["doc"],
  song: ["audio"],
  songs: ["audio"],
  sound: ["audio"],
  sounds: ["audio"],
  source: ["code"],
  spreadsheet: ["doc"],
  text: ["text"],
  track: ["audio"],
  tracks: ["audio"],
  video: ["video"],
  videos: ["video"],
  voice: ["audio"],
  wallpaper: ["image"],
  zip: ["archive"],
  zips: ["archive"],
};

/** File kind -> auto-file folder name. Shared so the same upload lands in the same folder on both clients. A kind with no folder is not auto-filed. */
export const KIND_FOLDERS: Readonly<Record<string, string>> = {
  image: "Images",
  video: "Videos",
  audio: "Audio",
  pdf: "Documents",
  doc: "Documents",
  text: "Documents",
  code: "Code",
  archive: "Archives",
};

/** Folder-name synonym groups for smart auto-filing. Two names that share a group describe the same concept, so an AI suggestion of 'Screenshots' can match an existing 'Pictures' folder. Shared so both clients match the same way. */
export const FOLDER_CONCEPTS: readonly (readonly string[])[] = [
  ["image", "picture", "photo", "pic", "snapshot", "wallpaper", "screenshot", "screengrab", "screencap"],
  ["screenshot", "screengrab", "screencap", "screencapture"],
  ["video", "movie", "film", "clip", "footage", "recording"],
  ["audio", "music", "song", "sound", "soundtrack", "track", "podcast", "voice"],
  ["document", "doc", "pdf", "paper", "letter", "report", "file"],
  ["receipt", "invoice", "bill"],
  ["code", "source", "script", "program", "snippet", "dev"],
  ["archive", "zip", "backup", "compressed"],
  ["note", "memo"],
  ["data", "dataset", "csv", "spreadsheet", "sheet"],
  ["diagram", "chart", "graph", "figure"],
];
