package com.cloudcast.app.ui.preview

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.cloudcast.app.ui.common.ErrorText
import com.cloudcast.app.ui.common.LoadingContent
import com.cloudcast.app.ui.common.MaterialSymbol
import com.cloudcast.app.ui.theme.AppIcons

@Composable
internal fun AiAnalysisCard(
    aiSummary: String?,
    aiModel: String?,
    aiLoading: Boolean,
    aiError: String?,
    onAnalyze: (regenerate: Boolean) -> Unit,
    modifier: Modifier = Modifier,
) {
    Surface(
        shape = RoundedCornerShape(8.dp),
        color = MaterialTheme.colorScheme.primaryContainer,
        border = androidx.compose.foundation.BorderStroke(1.dp, MaterialTheme.colorScheme.outline),
        modifier = modifier,
    ) {
        Column(Modifier.padding(14.dp)) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(8.dp),
            ) {
                MaterialSymbol(
                    AppIcons.autoAwesome,
                    size = 18,
                    tint = MaterialTheme.colorScheme.onPrimaryContainer,
                )
                Text(
                    "AI analysis",
                    fontWeight = FontWeight.Bold,
                    fontSize = 13.sp,
                    color = MaterialTheme.colorScheme.onPrimaryContainer,
                )
            }
            Spacer(Modifier.size(10.dp))
            if (aiSummary == null) {
                OutlinedButton(
                    onClick = { onAnalyze(false) },
                    modifier = Modifier.fillMaxWidth(),

                    shape = RoundedCornerShape(8.dp),
                    enabled = !aiLoading,
                ) {
                    LoadingContent(isLoading = aiLoading) {
                        Text("Analyze with AI")
                    }
                }
            } else {
                Text(
                    aiSummary,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface,
                )
                aiModel?.let { model ->
                    Spacer(Modifier.size(8.dp))
                    Text(
                        "Generated by $model",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                Spacer(Modifier.size(12.dp))

                TextButton(
                    onClick = { onAnalyze(true) },
                    enabled = !aiLoading,
                ) {
                    LoadingContent(isLoading = aiLoading) {
                        MaterialSymbol(AppIcons.refresh, size = 18)
                        Spacer(Modifier.width(8.dp))
                        Text("Regenerate")
                    }
                }
            }
            aiError?.let { err ->
                Spacer(Modifier.size(8.dp))
                ErrorText(err)
            }
        }
    }
}
