#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const C = JSON.parse(readFileSync(join(ROOT, "shared", "contract.json"), "utf8"));

const strip = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith("_")));
const enums = strip(C.enums);

const BANNER = (lang, src = "shared/contract.json") =>
  `// AUTO-GENERATED by shared/generate.mjs from ${src} - DO NOT EDIT.\n` +
  `// Run \`node shared/generate.mjs\`${lang === "kt" ? " (also runs as a Gradle preBuild task)" : " (or `npm run tokens`)"} to regenerate.\n\n`;

const camel = (s) => s.replace(/[-_](.)/g, (_, c) => c.toUpperCase());
const pascal = (s) => s.charAt(0).toUpperCase() + camel(s).slice(1);

const tsEnum = (name, def) => {
  const vs = def.values;
  const T = pascal(name);
  return (def._doc ? `/** ${def._doc} */\n` : "") +
    `export const ${name.toUpperCase()} = [${vs.map((v) => `"${v}"`).join(", ")}] as const;\n` +
    `export type ${T} = (typeof ${name.toUpperCase()})[number];\n`;
};

const ts = BANNER("ts") +
  Object.entries(enums).map(([n, d]) => tsEnum(n, d)).join("\n");
mkdirSync(join(ROOT, "web", "src", "api"), { recursive: true });
writeFileSync(join(ROOT, "web", "src", "api", "contract.generated.ts"), ts);
console.log("contract: generated web/src/api/contract.generated.ts.");

const ktEnum = (name, def) => {
  const T = pascal(name);
  const constName = (v) => v.replace(/[-_](.)/g, (_, c) => c.toUpperCase()).replace(/^./, (c) => c.toUpperCase());
  return (def._doc ? `/** ${def._doc} */\n` : "") +
    `enum class ${T}(val wire: String) {\n` +
    def.values.map((v) => `    ${constName(v)}("${v}"),`).join("\n") + "\n" +
    `    ;\n` +
    `    override fun toString() = wire\n` +
    `    companion object {\n` +
    `        fun from(wire: String): ${T}? = entries.firstOrNull { it.wire == wire }\n` +
    `    }\n}\n`;
};

const ktEnums = BANNER("kt") +
  "package com.cloudcast.app.core\n\n" +
  Object.entries(enums).map(([n, d]) => ktEnum(n, d)).join("\n");

const KT_CORE = join(ROOT, "app", "app", "src", "main", "java", "com", "cloudcast", "app", "core");
mkdirSync(KT_CORE, { recursive: true });
writeFileSync(join(KT_CORE, "Contract.kt"), ktEnums);
console.log("contract: generated core/Contract.kt.");

const F = JSON.parse(readFileSync(join(ROOT, "shared", "formats.json"), "utf8"));
const kinds = strip(F.fileKinds);
const searchWords = strip(F.searchWords);
const kindFolders = strip(F.kindFolders);
const conceptGroups = F.folderConcepts.groups;

const list = (a, q = '"') => a.map((v) => `${q}${v}${q}`).join(", ");

const fmtTs = BANNER("ts", "shared/formats.json") +
  `/** ${F.fileKinds._comment.replace(/\s+/g, " ")} */\n` +
  Object.entries(kinds)
    .map(([k, v]) => `export const ${k.toUpperCase()}_EXTS: readonly string[] = [${list(v)}];\n`)
    .join("") +
  `\n` +
  `/** ${F.metaEnvelope._comment.replace(/\s+/g, " ")} */\n` +
  `export const META = { nameKey: "${F.metaEnvelope.nameKey}", mimeKey: "${F.metaEnvelope.mimeKey}", ` +
  `defaultMime: "${F.metaEnvelope.defaultMime}" } as const;\n\n` +
  `/** ${F.signInCode._comment.replace(/\s+/g, " ")} */\n` +
  `export const SIGN_IN_CODE = { alphabet: "${F.signInCode.alphabet}", ` +
  `length: ${F.signInCode.length}, group: ${F.signInCode.group} } as const;\n\n` +
  `/** ${F.userBlobs._comment.replace(/\s+/g, " ")} */\n` +
  `export const BLOB_KIND = { favorites: "${F.userBlobs.favorites}" } as const;\n\n` +
  `/** ${F.searchWords._comment.replace(/\s+/g, " ")} */\n` +
  `export const SEARCH_WORDS: Readonly<Record<string, readonly string[]>> = {\n` +
  Object.entries(searchWords)
    .map(([w, ks]) => `  ${w}: [${list(ks)}],\n`)
    .join("") +
  `};\n\n` +
  `/** ${F.kindFolders._comment.replace(/\s+/g, " ")} */\n` +
  `export const KIND_FOLDERS: Readonly<Record<string, string>> = {\n` +
  Object.entries(kindFolders)
    .map(([k, v]) => `  ${k}: "${v}",\n`)
    .join("") +
  `};\n\n` +
  `/** ${F.folderConcepts._comment.replace(/\s+/g, " ")} */\n` +
  `export const FOLDER_CONCEPTS: readonly (readonly string[])[] = [\n` +
  conceptGroups.map((g) => `  [${list(g)}],\n`).join("") +
  `];\n`;

mkdirSync(join(ROOT, "web", "src", "shared"), { recursive: true });
writeFileSync(join(ROOT, "web", "src", "shared", "formats.generated.ts"), fmtTs);
console.log("formats: generated web/src/shared/formats.generated.ts.");

const fmtKt = BANNER("kt", "shared/formats.json") +
  "package com.cloudcast.app.core\n\n" +
  `/** ${F.fileKinds._comment.replace(/\s+/g, " ")} */\n` +
  "object Formats {\n" +
  Object.entries(kinds)
    .map(([k, v]) => `    val ${k.toUpperCase()}_EXTS: Set<String> = setOf(${list(v)})\n`)
    .join("") +
  `\n` +
  `    /** ${F.metaEnvelope._comment.replace(/\s+/g, " ")} */\n` +
  `    const val META_NAME_KEY = "${F.metaEnvelope.nameKey}"\n` +
  `    const val META_MIME_KEY = "${F.metaEnvelope.mimeKey}"\n` +
  `    const val DEFAULT_MIME = "${F.metaEnvelope.defaultMime}"\n\n` +
  `    /** ${F.signInCode._comment.replace(/\s+/g, " ")} */\n` +
  `    const val CODE_ALPHABET = "${F.signInCode.alphabet}"\n` +
  `    const val CODE_LENGTH = ${F.signInCode.length}\n` +
  `    const val CODE_GROUP = ${F.signInCode.group}\n\n` +
  `    /** ${F.userBlobs._comment.replace(/\s+/g, " ")} */\n` +
  `    const val BLOB_KIND_FAVORITES = "${F.userBlobs.favorites}"\n\n` +
  `    /** ${F.searchWords._comment.replace(/\s+/g, " ")} */\n` +
  `    val SEARCH_WORDS: Map<String, Set<String>> = mapOf(\n` +
  Object.entries(searchWords)
    .map(([w, ks]) => `        "${w}" to setOf(${list(ks)}),\n`)
    .join("") +
  `    )\n\n` +
  `    /** ${F.kindFolders._comment.replace(/\s+/g, " ")} */\n` +
  `    val KIND_FOLDERS: Map<String, String> = mapOf(\n` +
  Object.entries(kindFolders)
    .map(([k, v]) => `        "${k}" to "${v}",\n`)
    .join("") +
  `    )\n\n` +
  `    /** ${F.folderConcepts._comment.replace(/\s+/g, " ")} */\n` +
  `    val FOLDER_CONCEPTS: List<Set<String>> = listOf(\n` +
  conceptGroups.map((g) => `        setOf(${list(g)}),\n`).join("") +
  `    )\n` +
  "}\n";

writeFileSync(join(KT_CORE, "Formats.kt"), fmtKt);
console.log("formats: generated core/Formats.kt.");
