// AUTO-GENERATED by theme/generate.mjs from theme/colors.json - DO NOT EDIT.
// Run `npm run tokens` (or `node theme/generate.mjs`) to regenerate.

export interface ModeColors {
  primary: string;
  primaryHover: string;
  primaryTint: string;
  page: string;
  surface: string;
  inputBg: string;
  border: string;
  divider: string;
  inkHeading: string;
  strong: string;
  body: string;
  secondary: string;
  muted: string;
  faint: string;
  navActiveBg: string;
  cardShadow: string;
  aiBorder: string;
  aiDivider: string;
  aiBg: string;
  aiHeading: string;
  aiIcon: string;
  selectedBorder: string;
  unreadRowBg: string;
  rowHoverBg: string;
  dropVeil: string;
  moveHoverBg: string;
}

export interface ThemeColors extends ModeColors {
  accents: { success: string; successText: string; successTextDark: string; successBgLight: string; successBgDark: string; warning: string; warningBgLight: string; warningBgDark: string; favorite: string; secondaryLight: string; secondaryDark: string; dangerBorderLight: string; dangerBorderDark: string; aiMetaLight: string; aiMetaDark: string };
  selectionTint: string;
  selectionBorder: string;
}

export const COLORS: Record<"light" | "dark", ModeColors> = {
  "light": {
    "primary": "#7C3AED",
    "primaryHover": "#6D28D9",
    "primaryTint": "#EFEAFB",
    "page": "#F5F3FA",
    "surface": "#FFFFFF",
    "inputBg": "#FAF9FD",
    "border": "#E5E1EF",
    "divider": "#E5E1EF",
    "inkHeading": "#1F1B2E",
    "strong": "#39354A",
    "body": "#4A4658",
    "secondary": "#6B6680",
    "muted": "#9A95A6",
    "faint": "#C2BCD0",
    "navActiveBg": "#EFEAFB",
    "cardShadow": "0 1px 3px rgba(20,16,40,.08)",
    "aiBorder": "#E3DDF7",
    "aiDivider": "#DDD5F2",
    "aiBg": "#F7F4FF",
    "aiHeading": "#7C3AED",
    "aiIcon": "#A87BFF",
    "selectedBorder": "#D9CCF7",
    "unreadRowBg": "#F8F7FD",
    "rowHoverBg": "#F2F0F7",
    "dropVeil": "rgba(248,247,253,0.82)",
    "moveHoverBg": "#FAF9FD"
  },
  "dark": {
    "primary": "#7C3AED",
    "primaryHover": "#8B5CF6",
    "primaryTint": "#241F44",
    "page": "#0C0B11",
    "surface": "#15131D",
    "inputBg": "#0C0B11",
    "border": "#2E2A3C",
    "divider": "#2E2A3C",
    "inkHeading": "#F2F0F7",
    "strong": "#D6D2E0",
    "body": "#C4BFD4",
    "secondary": "#9C97A8",
    "muted": "#9C97A8",
    "faint": "#4F4A5E",
    "navActiveBg": "#241F44",
    "cardShadow": "0 1px 3px rgba(8,6,20,.4)",
    "aiBorder": "#2C2550",
    "aiDivider": "#2C2550",
    "aiBg": "#1A1535",
    "aiHeading": "#C9BCFF",
    "aiIcon": "#B89BFF",
    "selectedBorder": "#39354A",
    "unreadRowBg": "rgba(124,58,237,0.1)",
    "rowHoverBg": "rgba(124,58,237,0.14)",
    "dropVeil": "rgba(12,11,17,0.82)",
    "moveHoverBg": "rgba(255,255,255,0.03)"
  }
};

export const ACCENTS = {
  "success": "#1F9D57",
  "successText": "#1A8449",
  "successTextDark": "#35A768",
  "successBgLight": "#EFF8F3",
  "successBgDark": "#0F211C",
  "warning": "#D9542B",
  "warningBgLight": "#FCF3F0",
  "warningBgDark": "#2B1615",
  "favorite": "#F5A623",
  "secondaryLight": "#1F1B2E",
  "secondaryDark": "#B89BFF",
  "dangerBorderLight": "#F2C4C4",
  "dangerBorderDark": "#813725",
  "aiMetaLight": "#6C6491",
  "aiMetaDark": "#9A8FCF"
} as const;

export const SELECTION_TINT = "rgba(124,58,237,0.12)";
export const SELECTION_BORDER = "#7C3AED";
export const PRIMARY = "#7C3AED";
export const WARNING = "#D9542B";
export const SUCCESS = "#1F9D57";
export const FAVORITE = "#F5A623";
export const STRONG = "#39354A";
export const SECONDARY = "#6B6680";
export const LOGO_DOT = "#CDBDF5";
export const GRADIENT_END = "#A87BFF";
export const HOVER_ROW = "#F2F0F7";
export const HOVER_ROW_ALT = "#F8F7FD";
export const DROP_OVERLAY = "rgba(248,247,253,0.82)";
export const HATCH = {"light1":"#F1EEF9","light2":"#EFEAFB","dark1":"#1A1535","dark2":"#211A40"} as const;
export const WHITE = "#FFFFFF";
export const BLACK = "#000000";
export const OVERLAY_PRIMARY_HOVER = "rgba(124,58,237,0.05)";
export const OVERLAY_PRIMARY_DRAG = "rgba(124,58,237,0.07)";
export const OVERLAY_WARNING_HOVER = "rgba(217,84,43,0.06)";
export const ON_PRIMARY_BORDER = "rgba(255,255,255,0.5)";
export const SCRIM = "rgba(0,0,0,0.92)";
export const GLASS = "rgba(255,255,255,0.92)";
export const SHADOW_INK = {"light":"20, 16, 40","dark":"8, 6, 20"} as const;
export const LOGO = {
  "unit": 64,
  "puffs": [
    {
      "cx": 18,
      "cy": 34.5,
      "r": 9.5
    },
    {
      "cx": 31.5,
      "cy": 27.5,
      "r": 11.5
    },
    {
      "cx": 45,
      "cy": 33,
      "r": 10
    }
  ],
  "base": {
    "x": 6,
    "y": 35,
    "w": 52,
    "h": 13,
    "r": 6.5
  },
  "launcher": {
    "viewport": 108,
    "safe": 74,
    "background": "#EFEAFB"
  },
  "wordmark": {
    "first": "Cloud",
    "second": "Cast",
    "weight": 700,
    "tracking": -0.02
  }
} as const;
export const LOGO_PATH = "M8.5,34.5a9.5,9.5 0 1 1 19,0a9.5,9.5 0 1 1 -19,0z M20,27.5a11.5,11.5 0 1 1 23,0a11.5,11.5 0 1 1 -23,0z M35,33a10,10 0 1 1 20,0a10,10 0 1 1 -20,0z M6,41.5a6.5,6.5 0 0 1 6.5,-6.5h39a6.5,6.5 0 0 1 6.5,6.5v0a6.5,6.5 0 0 1 -6.5,6.5h-39a6.5,6.5 0 0 1 -6.5,-6.5z";
export const LOGO_MARK = {"light":"#6D28D9","dark":"#8B5CF6"} as const;
